### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ekuiter** [ekuiter/torte#1]
The following issues show the general roadmap for the future development of torte.

## Extraction

- [ ] https://github.com/torvalds/linux/commit/f9afce4f32e9a120fc902fa6c9e0b90ad799a6ec this will break extraction due to the new keyword (though the keyword is barely used)
- [ ]  can i use LLMs to support integrating new systems into torte? let it figure out itself how to extract the entire history, based on previous integrations? or at least doing the grunt work and ask me for confirmation only?
- [ ] some of these systems go way back than their first tags, which means that we miss out on a lot of history. at the same time, the tagged releases are probably intended to be used in practice. maybe add some optional support to sample (e.g., yearly) before the first tag and after the last tag? or look up the dates of early releases of each system and tag those explicitly in each history in a post clone hook?
- [ ] extract the entire commit histories not only for BusyBox, but for all other systems as well (requires generating KConfig file repositories for some, also require knowledge about what are relevant KConfig files per system)

<img width="863" height="729" alt="Image" src="https://github.com/user-attachments/assets/2ae12cb2-fa07-43a2-af31-18575c7be340" />

## Transformation

* [ ] clausy hybrid CNF transformation
* [ ] allow configurable thresholds for KConfigReader, Z3, and FeatJAR
* [ ] create megamodel by applying total transformation
* [ ] more CNF transformations ([FLOTTER](https://www.mpi-inf.mpg.de/departments/automation-of-logic/software/spass-workbench/classic-spass-theorem-prover/download), https://github.com/vprover/vampire/search?q=clausify, http://fmv.jku.at/limboole/)

## Analysis

* [ ] generalize computation of configs/config types (read-linux-configs for other systems) - it would be best to completely remove read-kconfig-configs-helper as its own stage and integrate it fully into the extraction, so it can profit from the generated KConfig files created by some systems (possibly this could even count as its own "extractor", which like ConfigFix needs no binding, and call make in that extraction routine?) 
* [ ] improve python script reuse across experiments, run a notebook stage for every experiment
    * [ ] possibly move features.dat computation out in own stage, which only has the purpose of creating new csv files including all information on features and their diagrams
    * [ ] review ConfigFix experiment files and de duplicate them
    * [ ] automate this with an LLM? once I got the CSV files, the LLMs can basically completely take over with designing plots and cleaning data frames and so on. so torte should really focus on everything to get the CSV files, because the afterward stuff can mostly be taken over by AI today.
* [ ] unify files by removing config prefix?? or not? so we can look up variables (relevant for ASE reproduction)
* [ ] (relevant for ASE reproduction) https://github.com/ekuiter/tseitin-or-not-tseitin/blob/main/stage3/solve.sh#L72 defines a strategy to only select features that are available in all formulas. the easiest way to reproduce this would be by making available to compute the intersection of two feature sets (we could also generalize the unconstrained diff function to a general set difference)
* [ ] for the TOSEM and ICSE experiments, enable `--options kconfigreader-tristate`, which slightly improves accuracy of results and more than slightly improves solving performance
* [ ] better interactive websites with https://quarto.org/
* [ ] integrate differencing - evaluate pairs of formulas for differencing (how to pass through timeout options too clausy? how to handle CSV output of that script?)

## Experiments

* [ ] go through all experiments and make sure they are fully functional
* [ ] work towards reproducing ASE'22 evaluation (e.g., add core/dead feature calculation)

## Execution

* [ ] add script that exports and imports ALL docker images to ensure better reproducibility if some image is no longer buildable (possibly use OCI image format)
* [ ] adapt torte to be executable on high-performance clusters (project topic?)
* [ ] develop a server backend for torte (see deprecated thesis topics)
* [ ] reproduce the results of existing evaluations (e.g., TypeChef) with other CNF transformations and/or KConfig extractors (thesis topic?)
* [ ] add virtualbox/vagrant image for easier reproduction, add vagrant/qemu amd64 environment for users on macs that have issues
* [ ] add graphviz visualization of stages

```
have claude work on revamping torte in the background? (eval script reuse, ASE reproduction/switch from R to python; use golden CSV output as oracle; Ralph loop?)

    use codex etc. to fully and automatedly:
    - rewrite torte to python+uv (it was a questionable idea to use bash from a performance POV, and hard to understand from outsiders). or even rust?? (probably only after dissertation)
    - add a server Backend+frontend for on-demand feature model extraction+basic analyses
    - rewrite PhD thesis to interactive experiments on one website, which can get auto-updated to new versions of systems if they get released (e.g., via cronjob)
    - put it all on one central torte hub: readme, dashboard, research, phd thesis, ...

    To do so, please make sure you really understand the architecture (also explained in paper.pdf). If you're not sure, ask me! Map out all the necessary changes in a .md plan file, which you use to track progress. Chop it up into reviewable chunks, each of which you git-commit individually with a helpful description - I will review your commits later.
    use torte CI mode to determine golden CSV outputs, ignoring time measurements and parallelism (add an option to omit those)
```

```
in the long run, rename torte/experiments/* into paper-appropriate directories (e.g., tosem25) where possible. also make all notebooks executable with run-notebook (and improve notebook reuse). for phd-thesis, make one overarching experiment that calls (analogous to a multipass experiment) the paper subexperiments. each paper experiment may then use an environment variable to encode variations needed for the phd thesis. this way, i avoid duplicating all experiments for the thesis, yet stil get to make smaller adjustments if needed. i can also print the command needed to reproduce each paper (in the thesis or paper version) at the beginning of each chapter.
``

```
add some automation to torte that auto-pushes a repo with an experiment's result report (e.g., a jupyter notebook). so, i could just run torte overnight on whatever machine (my own or a server or whatever) and it pushes results itself to some github-pages endpoint or something. that way, torte does not have to run on the machine that serves results, which is a helpful and flexible decoupling. also, i could collect all files in all stages of the LAST analyzed FM version, zip them up, and upload them as well - as a tradeoff, to publish at least recent versions of feature models easily online on a dashboard
```

## Legacy

**Enhancements**

* [ ] upgrade Z3 to 4.12.1 (or even a newer version), see https://github.com/Z3Prover/z3/issues/6577
* [ ] test and improve error handling for missing values (NA), e.g., that failed extractions/transformations propagate appropriately to the other stages (or are ignored)
* [ ] Z3: for DIMACS, some solvers require that "c " lines occur before "p cnf", Z3 does not do that correctly
* [ ] find out license for each committed blob/binary and document in readme
* [ ] treat `Killed` (due to OOM killer) as a failure
* [ ] move `linux-configs` and `linux-config-types` out of Linux (allow for general projects)
* [ ] create a mode which allows me to input a CSV list of feature models I'd like to extract (so it becomes possible to dynamically extract arbitrary models)

**Solvers**

* [ ] add ganak, winner of 2024's MCC
